name: Pruebas Laravel con PHPUnit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Configurar PHP 8.2
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, bcmath, pdo_mysql
        coverage: none

    - name: Instalar dependencias
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Copiar archivo de entorno
      run: cp .env.example .env

    - name: Generar clave de aplicación
      run: php artisan key:generate

    - name: Ejecutar migraciones
      run: php artisan migrate --env=testing

    - name: Ejecutar pruebas
      run: vendor/bin/phpunit
